#!/usr/bin/env bash
set -euo pipefail

stamp="$(date -u +%Y%m%dT%H%M%SZ)"
ssh_dir="${HOME}/.ssh"
mkdir -p "${ssh_dir}"
chmod 700 "${ssh_dir}"

config_path="${ssh_dir}/config"
if [ -f "${config_path}" ]; then
  cp -p "${config_path}" "${config_path}.backup-${stamp}"
fi

identity_lines=""
for key in \
  "${ssh_dir}/id_ed25519" \
  "${ssh_dir}/id_rsa" \
  "${ssh_dir}/kolibri_ai_platform_deploy_ed25519" \
  "${ssh_dir}/kolibri_factory_github_ed25519" \
  "${ssh_dir}/kolibri_github_deploy_ed25519" \
  "${ssh_dir}/ubuntu_home_shared_ed25519"
do
  if [ -f "${key}" ]; then
    identity_lines="${identity_lines}  IdentityFile ${key}
"
  fi
done

tmp_config="$(mktemp)"
{
  cat <<'EOF'
# Kolibri Factory unified SSH topology.
# Generated by thin-client dispatcher. No secrets are stored in this file.

Host *
  ServerAliveInterval 30
  ServerAliveCountMax 3
  ConnectTimeout 10
  ConnectionAttempts 1
  StrictHostKeyChecking accept-new
  PasswordAuthentication no
  KbdInteractiveAuthentication no
  PreferredAuthentications publickey
  IdentitiesOnly yes
EOF
  printf "%s" "${identity_lines}"
  cat <<'EOF'

Host github.com
  HostName github.com
  User git

Host kolibri-primary-codex primary-codex primary-candidate kolibri-primary-candidate control-standby primary.kolibri.internal primary-candidate.kolibri.internal
  HostName 78.17.4.108
  User root

Host kolibri-main main control kolibri-main-api kolibri-main-api-direct main.kolibri.internal control.kolibri.internal
  HostName 104.253.43.117
  User root

Host kolibri-home-root home-root coordinator-root home.kolibri.internal-root
  HostName 10.99.0.1
  User root
  ProxyJump kolibri-main

Host kolibri-home home coordinator plastilin home.kolibri.internal coordinator.kolibri.internal
  HostName 10.99.0.1
  User ladik
  ProxyJump kolibri-main

Host kolibri-uiap uiap rag kolibri-rag-knowledge kolibri-rag-knowledge-direct uiap.kolibri.internal rag.kolibri.internal
  HostName 31.57.26.151
  User root

Host kolibri-qjns qjns tools kolibri-tools-executor kolibri-tools-executor-direct qjns.kolibri.internal tools.kolibri.internal
  HostName 217.60.63.97
  User root

Host kolibri-9fts 9fts inference kolibri-inference-recovery kolibri-inference-recovery-direct 9fts.kolibri.internal inference.kolibri.internal
  HostName 94.183.235.154
  User root

Host kolibri-new new worker-backup kolibri-worker-backup kolibri-worker-backup-direct new.kolibri.internal worker-backup.kolibri.internal
  HostName 109.248.161.39
  User root

Host reserve242 kolibri-qa-security qa-security reserve242.kolibri.internal
  HostName 31.57.26.242
  User root

Host hostvds-highload highload kolibri-ci-build-highload ci-build-highload highload.kolibri.internal
  HostName 45.38.139.182
  User root

Host hostvds-agent-01 agent-01 kolibri-backend-lead backend-lead
  HostName 31.57.27.128
  User root

Host hostvds-agent-02 agent-02 kolibri-frontend-design frontend-design
  HostName 213.232.204.223
  User root

Host hostvds-agent-03 agent-03 kolibri-infra-network infra-network
  HostName 188.130.206.204
  User root

Host hostvds-agent-04 agent-04 kolibri-qa-browser qa-browser
  HostName 31.59.41.146
  User root

Host hostvds-agent-05 agent-05 kolibri-security-audit security-audit
  HostName 31.56.196.10
  User root

Host hostvds-agent-06 agent-06 kolibri-docs-knowledge docs-knowledge
  HostName 45.39.33.252
  User root

Host hostvds-agent-07 agent-07 kolibri-formulalm-eval formulalm-eval
  HostName 46.8.225.34
  User root

Host hostvds-agent-08 agent-08 kolibri-rag-eval rag-eval
  HostName 31.59.105.200
  User root

Host hostvds-agent-09 agent-09 kolibri-release-canary release-canary
  HostName 95.182.84.254
  User root

Host hostvds-agent-10 agent-10
  HostName 217.60.38.191
  User root

Host hostvds-paris-highload paris kolibri-paris-build-reserve paris-build-reserve
  HostName 95.182.83.60
  User root

Host server-kfrm kfrm heavy-tests heavy-tests.kolibri.internal
  HostName 217.60.63.31
  User root
EOF
} > "${tmp_config}"

install -m 600 "${tmp_config}" "${config_path}"
rm -f "${tmp_config}"

if [ "$(id -u)" -eq 0 ]; then
  tmp_hosts="$(mktemp)"
  awk '
    /^# BEGIN KOLIBRI FACTORY TOPOLOGY$/ {skip=1; next}
    /^# END KOLIBRI FACTORY TOPOLOGY$/ {skip=0; next}
    skip != 1 {print}
  ' /etc/hosts > "${tmp_hosts}"
  cat <<'EOF' >> "${tmp_hosts}"
# BEGIN KOLIBRI FACTORY TOPOLOGY
10.99.0.1 home.kolibri.internal coordinator.kolibri.internal
78.17.4.108 primary.kolibri.internal primary-candidate.kolibri.internal control-standby.kolibri.internal
104.253.43.117 main.kolibri.internal control.kolibri.internal kolibri-main-api
31.57.26.151 uiap.kolibri.internal rag.kolibri.internal kolibri-rag-knowledge
217.60.63.97 qjns.kolibri.internal tools.kolibri.internal kolibri-tools-executor
94.183.235.154 9fts.kolibri.internal inference.kolibri.internal kolibri-inference-recovery
109.248.161.39 new.kolibri.internal worker-backup.kolibri.internal kolibri-worker-backup
31.57.26.242 reserve242.kolibri.internal kolibri-qa-security
45.38.139.182 highload.kolibri.internal kolibri-ci-build-highload
31.57.27.128 agent-01.kolibri.internal kolibri-backend-lead
213.232.204.223 agent-02.kolibri.internal kolibri-frontend-design
188.130.206.204 agent-03.kolibri.internal kolibri-infra-network
31.59.41.146 agent-04.kolibri.internal kolibri-qa-browser
31.56.196.10 agent-05.kolibri.internal kolibri-security-audit
45.39.33.252 agent-06.kolibri.internal kolibri-docs-knowledge
46.8.225.34 agent-07.kolibri.internal kolibri-formulalm-eval
31.59.105.200 agent-08.kolibri.internal kolibri-rag-eval
95.182.84.254 agent-09.kolibri.internal kolibri-release-canary
217.60.38.191 agent-10.kolibri.internal
95.182.83.60 paris.kolibri.internal kolibri-paris-build-reserve
217.60.63.31 heavy-tests.kolibri.internal server-kfrm
# END KOLIBRI FACTORY TOPOLOGY
EOF
  install -m 644 "${tmp_hosts}" /etc/hosts
  rm -f "${tmp_hosts}"
fi

echo "installed kolibri ssh topology for $(id -un) on $(hostname)"
