import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const css = readFileSync(new URL("../src/App.css", import.meta.url), "utf8");
const html = readFileSync(new URL("../index.html", import.meta.url), "utf8");
const brand = readFileSync(new URL("../src/shell/Brand.jsx", import.meta.url), "utf8");
const navigation = readFileSync(new URL("../src/shell/useShellNavigation.js", import.meta.url), "utf8");
const shellNavigation = readFileSync(new URL("../src/shell/ShellNavigation.jsx", import.meta.url), "utf8");
const stageLayout = readFileSync(new URL("../src/workbench/useStageLayout.js", import.meta.url), "utf8");
const toolDock = readFileSync(new URL("../src/shell/ToolDock.jsx", import.meta.url), "utf8");
const toolMenu = readFileSync(new URL("../src/shell/ComposerToolMenu.jsx", import.meta.url), "utf8");
const composer = readFileSync(new URL("../src/shell/Composer.jsx", import.meta.url), "utf8");
const mobileWindow = readFileSync(new URL("../src/workbench/MobileWindow.jsx", import.meta.url), "utf8");
const dialogFocus = readFileSync(new URL("../src/app/useDialogFocus.js", import.meta.url), "utf8");
const projectsWindow = readFileSync(new URL("../src/windows/ProjectsWindow.jsx", import.meta.url), "utf8");
const publicShell = readFileSync(new URL("../src/shell/PublicShell.jsx", import.meta.url), "utf8");
const projectWorkspace = readFileSync(new URL("../src/windows/ProjectWorkspace.jsx", import.meta.url), "utf8");
const workSummary = readFileSync(new URL("../src/windows/shared/WorkSummary.jsx", import.meta.url), "utf8");
const mobileCss = css.slice(css.indexOf("@media (max-width: 760px)"), css.indexOf("@media (max-width: 420px)"));

assert.match(css, /min-height:\s*100svh/);
assert.match(css, /@supports \(height:\s*100dvh\)/);
assert.match(css, /@media \(max-width:\s*760px\)/);
assert.match(css, /\.workbench-body\s*\{[^}]*overflow:\s*hidden/s);
assert.match(css, /\.stage-canvas,[\s\S]*?\.mobile-stage\s*\{[^}]*position:\s*relative/s);
assert.match(css, /\.kolibri-workbench\s*\{[^}]*grid-template-rows:\s*var\(--system-bar-height\) minmax\(0, 1fr\) auto/s);
assert.match(css, /\.composer-layer\s*\{[^}]*position:\s*relative/s);
assert.match(css, /\.mobile-window\s*\{/);
assert.match(css, /\.composer-layer\s*\{[^}]*var\(--safe-bottom\)/s);
assert.doesNotMatch(css.match(/\.composer-layer\s*\{[^}]*\}/s)?.[0] || "", /position:\s*(?:absolute|fixed)/);
assert.match(css, /\.floating-composer \.composer-send\s*\{[^}]*width:\s*44px[^}]*height:\s*44px/s);
assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*?\.tool-dock\s*\{[^}]*position:\s*fixed[^}]*transform:\s*translateX\(-105%\)/s);
assert.match(css, /\.tool-dock\.is-mobile-open\s*\{[^}]*pointer-events:\s*auto[^}]*transform:\s*translateX\(0\)/s);
assert.match(css, /\.navigation-scrim\.is-visible\s*\{[^}]*position:\s*fixed/s);
assert.match(css, /\.composer-layer\.is-embedded \.tool-menu,[\s\S]*?position:\s*fixed[^}]*bottom:\s*0/s);
assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*?\.mobile-stage\s*\{[^}]*width:\s*100%/s);
assert.match(css, /@media \(prefers-reduced-motion:\s*reduce\)/);
assert.match(css, /button:focus-visible/);
assert.match(css, /--safe-top:\s*env\(safe-area-inset-top/);
assert.match(css, /--shell-viewport-offset-top:\s*0px/);
assert.match(css, /\.selected-tool\s*\{[^}]*max-width:\s*100%/s);
assert.match(css, /\.selected-tool > span\s*\{[^}]*text-overflow:\s*ellipsis/s);
assert.match(css, /\.mobile-window\s*\{[^}]*var\(--safe-bottom\)/s);
assert.match(css, /\.mobile-window > header button\s*\{[^}]*width:\s*44px[^}]*height:\s*44px/s);
assert.match(mobileCss, /\.floating-composer > button\s*\{[^}]*width:\s*44px[^}]*height:\s*44px/s);
assert.doesNotMatch(mobileCss, /\.floating-composer(?: > button| \.composer-send)\s*\{[^}]*(?:width|height):\s*(?:40|42)px/s);
assert.doesNotMatch(html, /user-scalable=no/);
assert.doesNotMatch(html, /maximum-scale=1/);
assert.match(html, /href="\/kolibri-bird\.png"/);
assert.match(brand, /aria-controls="kolibri-navigation"/);
assert.match(brand, /<button[\s\S]*?onClick=\{onActivate\}/s);
assert.match(navigation, /useMobileSurface/);
assert.match(stageLayout, /MOBILE_SURFACE_QUERY = "\(max-width: 760px\)"/);
assert.match(navigation, /type: "PREVIEW_OPEN"/);
assert.match(navigation, /setTimeout\(\(\) => dispatch\(\{ type: "PREVIEW_CLOSE" \}\), 180\)/);
assert.match(navigation, /type: "PIN_TOGGLE"/);
assert.match(navigation, /type: "MOBILE_TOGGLE"/);
assert.match(shellNavigation, /className=\{`navigation-scrim/);
assert.match(toolDock, /inert=\{mobile && !mobileOpen\}/);
assert.match(toolDock, /className=\{`tool-dock/);
assert.match(toolMenu, /className="tool-menu-scrim"/);
assert.match(toolMenu, /id="kolibri-composer-tools"/);
assert.match(mobileWindow, /useDialogFocus/);
assert.match(mobileWindow, /tabIndex=\{-1\}/);
assert.match(dialogFocus, /event\.key !== "Tab"/);
assert.match(dialogFocus, /element\?\.isConnected/);
assert.match(dialogFocus, /\[inert\], \[aria-hidden='true'\]/);
assert.match(projectsWindow, /role="alertdialog"/);
assert.match(projectsWindow, /data-dialog-initial-focus/);
assert.match(projectsWindow, /createPortal\(dialogNode, globalThis\.document\.body\)/);
assert.match(dialogFocus, /focusLayers\.at\(-1\)/);
assert.match(mobileCss, /\.estimate-metadata input\s*\{[^}]*min-height:\s*44px/s);
assert.doesNotMatch(css, /estimate-export-placeholders/);
assert.match(publicShell, /<ShellHeader[\s\S]*<ShellWorkbench[\s\S]*<ShellComposer/);
assert.doesNotMatch(projectWorkspace, /<Composer/);
assert.match(composer, /nativeEvent\?\.isComposing/);
assert.match(workSummary, /useDialogFocus\(panel, \{ open/);
assert.match(workSummary, /aria-modal="true"/);
assert.match(workSummary, /role="dialog"/);
assert.match(workSummary, /tabIndex=\{-1\}/);
assert.match(workSummary, /className="work-summary-retry"/);
assert.match(mobileCss, /\.work-summary-retry,[\s\S]*?min-height:\s*44px/s);

console.log("Kolibri responsive layout and accessibility guard passed");
