import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const css = readFileSync(new URL("../src/App.css", import.meta.url), "utf8");
const html = readFileSync(new URL("../index.html", import.meta.url), "utf8");
const brand = readFileSync(new URL("../src/shell/Brand.jsx", import.meta.url), "utf8");
const navigation = readFileSync(new URL("../src/shell/useShellNavigation.js", import.meta.url), "utf8");
const shellNavigation = readFileSync(new URL("../src/shell/ShellNavigation.jsx", import.meta.url), "utf8");
const stageLayout = readFileSync(new URL("../src/workbench/useStageLayout.js", import.meta.url), "utf8");
const toolDock = readFileSync(new URL("../src/shell/ToolDock.jsx", import.meta.url), "utf8");
const toolMenu = readFileSync(new URL("../src/shell/ComposerToolMenu.jsx", import.meta.url), "utf8");

assert.match(css, /--composer-bottom-gap:\s*18px/);
assert.match(css, /--composer-bottom-gap-mobile:\s*14px/);
assert.match(css, /min-height:\s*100svh/);
assert.match(css, /@supports \(height:\s*100dvh\)/);
assert.match(css, /@media \(max-width:\s*760px\)/);
assert.match(css, /\.workbench-body\s*\{[^}]*overflow:\s*hidden/s);
assert.match(css, /\.stage-canvas,[\s\S]*?\.mobile-stage\s*\{[^}]*position:\s*relative/s);
assert.match(css, /\.composer-layer\s*\{[^}]*position:\s*absolute/s);
assert.match(css, /\.mobile-window\s*\{/);
assert.match(css, /\.composer-layer\s*\{[^}]*var\(--safe-bottom\)/s);
assert.match(css, /\.floating-composer \.composer-send\s*\{[^}]*width:\s*44px[^}]*height:\s*44px/s);
assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*?\.tool-dock\s*\{[^}]*position:\s*fixed[^}]*transform:\s*translateX\(-105%\)/s);
assert.match(css, /\.tool-dock\.is-mobile-open\s*\{[^}]*pointer-events:\s*auto[^}]*transform:\s*translateX\(0\)/s);
assert.match(css, /\.navigation-scrim\.is-visible\s*\{[^}]*position:\s*fixed/s);
assert.match(css, /\.composer-layer\.is-embedded \.tool-menu,[\s\S]*?position:\s*fixed[^}]*bottom:\s*0/s);
assert.match(css, /@media \(max-width:\s*760px\)[\s\S]*?\.mobile-stage\s*\{[^}]*width:\s*100%/s);
assert.match(css, /@media \(prefers-reduced-motion:\s*reduce\)/);
assert.match(css, /button:focus-visible/);
assert.doesNotMatch(html, /user-scalable=no/);
assert.doesNotMatch(html, /maximum-scale=1/);
assert.match(html, /href="\/kolibri-bird\.png"/);
assert.match(brand, /aria-controls="kolibri-navigation"/);
assert.match(brand, /<button[\s\S]*?onClick=\{onActivate\}/s);
assert.match(navigation, /useMobileSurface/);
assert.match(stageLayout, /MOBILE_SURFACE_QUERY = "\(max-width: 760px\)"/);
assert.match(navigation, /type: "PREVIEW_OPEN"/);
assert.match(navigation, /setTimeout\(\(\) => dispatch\(\{ type: "PREVIEW_CLOSE" \}\), 180\)/);
assert.match(navigation, /type: "PIN_TOGGLE"/);
assert.match(navigation, /type: "MOBILE_TOGGLE"/);
assert.match(shellNavigation, /className=\{`navigation-scrim/);
assert.match(toolDock, /inert=\{mobile && !mobileOpen\}/);
assert.match(toolDock, /className=\{`tool-dock/);
assert.match(toolMenu, /className="tool-menu-scrim"/);
assert.match(toolMenu, /id="kolibri-composer-tools"/);

console.log("Kolibri responsive layout and accessibility guard passed");
