export const THREAD_UI_TEXT = {
	WELCOME_TITLE: "Чем я могу помочь сегодня?",
	WELCOME_SUBTITLE:
		"Kolibri соберёт исходные данные, посчитает смету, подготовит документы и покажет основания — спросите что угодно.",
	RUN_PROGRESS_TEXT: "Kolibri выполняет задачу",
	RUN_PROGRESS_TOOLTIP: "К последнему сообщению",
	STATUS_IDLE: "Диалог с Kolibri",
	DRAFT_EMPTY: "Войдите, чтобы написать Kolibri",
	DRAFT_AUTH: "Спросите что угодно…",
	DRAFT_AUTH_COMPACT: "Спросите что угодно…",
	THREAD_LABEL_EMPTY_STATE: "aui_empty-state",
	MESSAGE_GROUP_ROLE: "log",
	MOBILE_STARTER_ACTION_CLASS: "aui-mobile-starter-action",
	TOOLTIP_PREVIOUS_BRANCH: "Предыдущая версия",
	TOOLTIP_NEXT_BRANCH: "Следующая версия",
	TOOLTIP_COPY: "Копировать",
	TOOLTIP_EDIT: "Редактировать",
	TOOLTIP_DOWNLOAD_MARKDOWN: "Скачать ответ в Markdown",
	TOOLTIP_DOWNLOAD_ESTIMATE: "Скачать смету в PDF",
	TOOLTIP_SHARE_ESTIMATE: "Поделиться сметой",
	TOOLTIP_SHARE_TEXT: "Поделиться ответом",
	TOOLTIP_SHARE_ESTIMATE_DONE: "Смета передана",
	TOOLTIP_SHARE_TEXT_DONE: "Ответ передан",
	TOOLTIP_FEEDBACK_GOOD: "Хороший ответ",
	TOOLTIP_FEEDBACK_BAD: "Плохой ответ",
	TOOLTIP_RETRY: "Повторить ответ",
	TOOLTIP_ATTACH: "Войти, чтобы прикрепить файл",
	TOOLTIP_ATTACH_ENABLED: "Прикрепить файл",
	TOOLTIP_ATTACH_DISABLED: "Вложения пока недоступны",
	EDIT_CANCEL_LABEL: "Отмена",
	EDIT_SAVE_LABEL: "Сохранить",
	MESSAGE_ERROR_LABEL: "Ошибка сообщения",
	LABEL_CONTEXT_OPEN: "Показать контекст",
	LABEL_CONTEXT_CLOSE: "Скрыть контекст",
	LABEL_COMPOSE_SEND: "Отправить сообщение",
	LABEL_COMPOSE_EMPTY: "Введите сообщение, чтобы отправить",
	LABEL_COMPOSE_CANCEL: "Остановить ответ",
	LABEL_COMPOSE_DICTATE: "Начать голосовой ввод",
	LABEL_COMPOSE_DICTATE_STOP: "Остановить голосовой ввод",
	LABEL_DICTATE_UNAVAILABLE: "Голосовой ввод недоступен",
	TOOLTIP_SCROLL_TO_BOTTOM: "К последнему сообщению",
	TOOLTIP_DICTATE: "Голосовой ввод",
	TOOLTIP_DICTATE_STOP: "Остановить голосовой ввод",
	TOOLTIP_ATTENTION: "Kolibri работает",
	TOOLTIP_REASONING_ACTIVE: "Kolibri выполняет задачу",
	TOOLTIP_REASONING_IDLE: "Ход выполнения",
	REASONING_ACCEPTED_TEXT: "Запрос принят и связан с текущим проектом",
	REASONING_STREAMING_TEXT: "Готовится проверяемый результат",
	REASONING_DONE_TEXT: "Результат подготовлен",
	ERROR_MESSAGE_LABEL: "Ошибка сообщения",
	THREAD_VIEWPORT_ARIA_RELEVANT: "additions",
	THREAD_VIEWPORT_FOOTER_SLOT: "aui_thread-viewport-footer",
	EDIT_CANCEL: "Отмена",
	EDIT_SAVE: "Сохранить",
	THREAD_COMPOSER_OPEN_BUTTON_CLASS: "h-8 rounded-full px-3",
	LABEL_OPEN_ACCOUNT: "Войти",
	THREAD_COMPOSER_EDITOR_BUTTON_CLASS: "h-8 rounded-full px-3.5",
	SHARE_FALLBACK_TEXT: "Не удалось открыть системное меню отправки PDF.",
	SHARE_BROWSER_FALLBACK_TEXT: "Этот браузер не поддерживает системную отправку PDF.",
	SHARE_MESSAGE_PREPARE: "Готовлю PDF…",
	SHARE_MESSAGE_OPEN_SHARE: "Открываю системное меню отправки…",
	SHARE_SUCCESS_TOAST_TITLE: "Ответ Kolibri",
	SHARE_SUCCESS_FALLBACK_COPY_PREFIX:
		"PDF, Excel и Word сформированы из одной версии сметы.",
	THREAD_VIEWPORT_FOOTER_COMPACT_LABEL: "Быстрые действия",
	THREAD_VIEWPORT_WELCOME_LABEL: "Быстрый старт",
	THREAD_VIEWPORT_LOGIN_REQUIRED: "войдите в личный кабинет, чтобы использовать Kolibri",
	THREAD_COMPOSER_ATTACHMENT_ERROR_TYPE: "Не удалось добавить файл. Повторите попытку.",
	THREAD_COMPOSER_ATTACHMENT_ERROR_NOT_ACCEPTED: "Этот формат файла пока не поддерживается.",
	THREAD_COMPOSER_ATTACHMENT_ERROR_NO_ADAPTER: "Вложения пока недоступны.",
	THREAD_COMPOSER_SEND: "Отправить",
	REASONING_STATUS_COMPLETE: "Результат подготовлен",
	REASONING_STATUS_PREPARING: "Готовится проверяемый результат",
	REASONING_STATUS_REQUEST_ACCEPTED: "Запрос принят и связан с текущим проектом",
	THREAD_MESSAGE_GROUP_LABEL: "Диалог с Kolibri",
	THREAD_MESSAGE_GROUP_LOG_LABEL: "Диалог с Kolibri",
	TOOLTIP_MOBILE_HINT: "Спросите что угодно…",
	THREAD_INPUT_ARIA_LABEL: "Сообщение для Kolibri",
	THREAD_MOBILE_ACTIONS_ARIA: "Быстрые действия",
	SHARE_FALLBACK_PDF_ONLY: "Смета передана",
	THREAD_COMPOSER_SEND_DISABLED: "Введите сообщение, чтобы отправить",
	THREAD_COMPOSER_SEND_LABEL: "Отправить сообщение",
	GEN_UI_PROVENANCE: "Представление ИИ · не является подтверждением",
	GEN_UI_PANEL_ARIA: "Сгенерированное представление Kolibri",
	GEN_UI_DETAILS_SUMMARY: "Структура блока",
	GEN_UI_SOURCE_LABEL: "Безопасное описание сгенерированного интерфейса",
	SHARE_TEXT_PREFIX: "Ответ Kolibri",
	TOOLTIP_CANCEL_STREAM: "Остановить ответ",
	THREAD_MESSAGE_BRANCH_STATE_TEXT: " / ",
	THREAD_MESSAGE_BRANCH_DIVIDER: " / ",
	ACTIONBAR_COPY_TOOLTIP: "Копировать",
	RUN_STATUS_TEXT: "Колибри выполняет задачу",
	SHARE_ESTIMATE_REGION_PREFIX: "Регион: ",
	SHARE_ESTIMATE_TOTAL_PREFIX: "Итого: ",
} as const;

export const THREAD_UI_CLASS = {
	REASONING_ICON_ACTIVE: "size-3.5 shrink-0 animate-spin text-sky-600",
	REASONING_ICON_DONE: "size-3.5 shrink-0 text-emerald-600",
	INDICATOR: "animate-pulse font-sans",
	MOBILE_STARTER_BADGE: "aui-mobile-starter-action",
	ACTION_BAR_SPACE: "flex items-center gap-2",
	GROUP_WRAP: "min-w-0 max-w-full",
	EDIT_TOOLBAR_BUTTON: "h-8 rounded-full px-3.5",
	THREAD_COMPOSER_CANCEL_ICON: "aui-composer-cancel-icon size-3.5 fill-current",
	SPINNER_RUNNING: "size-4 shrink-0 animate-spin text-[#339cff]",
	COPY_ICON: "size-3.5",
	SHARE_ICON_CLASS: "size-3.5",
	ANIMATION_COPY_IN: "animate-in zoom-in-50 fade-in duration-200 ease-out",
	ANIMATION_COPY_DEFAULT: "animate-in zoom-in-75 fade-in duration-150",
	ACTION_FOOTER_PADDING_TOP: "pt-1.5",
	ACTION_FOOTER_HEIGHT: "min-h-7.5",
	EDIT_BUTTON_CLASS: "h-8 rounded-full px-3.5",
	THREAD_BRANCH_STATE_CLASS: "aui-branch-picker-state font-medium",
	THREAD_MESSAGE_ERROR_CLASS: "aui-message-error-message line-clamp-2",
	THREAD_COMPOSER_ERROR_ALERT: "text-destructive px-1.5 text-xs leading-relaxed",
	REASONING_SPACE: "space-y-2",
	REASONING_ICON_CONTAINER: "flex items-center gap-2",
	THREAD_MOBILE_STARTERS_WRAPPER: "aui-mobile-starter-action",
	THREAD_WELCOME_SUGGESTIONS_WRAPPER: "aui-thread-welcome-suggestions",
	THREAD_SEND_DISABLED: "aui-composer-send-disabled",
	THREAD_SCROLL_TO_BOTTOM: "aui-thread-scroll-to-bottom",
	COMPOSER_CSS_MOBILE_PLACEHOLDER: "aui-composer-placeholder-mobile",
	THREAD_ACTION_BUTTON_SIZE: "aui-composer-action-button size-7 rounded-full",
} as const;
