#!/usr/bin/env python3
"""Read-only exact-file-set gate for the selected immutable Home release.

The signed manifest is the complete allowlist.  Runtime-generated bytecode,
logs, caches, symlinks, missing bytes, and mode/digest drift are release
pollution rather than harmless implementation details.  This command never
repairs or removes files; it emits a bounded owner-facing repair sequence and
blocks activation until a separate approved repair restores the exact set.
"""

from __future__ import annotations

import argparse
import grp
import hashlib
import json
import os
import re
import stat
from pathlib import Path, PurePosixPath
from typing import Any


SCHEMA_VERSION = "kolibri.immutable-release-preflight.v1"
RELEASE_SCHEMA = "kolibri.release.v1"
DEFAULT_CURRENT = Path("/opt/kolibri-ai/current")
DEFAULT_RELEASE_ROOT = Path("/opt/kolibri-ai/releases")
MANIFEST_PATH = ".kolibri-release/manifest.json"
SIGNATURE_PATH = ".kolibri-release/manifest.sig"
MAX_MANIFEST_BYTES = 2 * 1024 * 1024
MAX_REPORTED_PATHS = 128
DEFAULT_OWNER_TOKEN = Path("/etc/kolibri/owner-api-token")
DEFAULT_OWNER_TOKEN_GROUP = "kolibri-agent"
OWNER_TOKEN_MODE = 0o640
MAX_OWNER_TOKEN_BYTES = 4 * 1024
SAFE_RELEASE_ID = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}")
SAFE_SHA256 = re.compile(r"[0-9a-f]{64}")
SAFE_MODES = frozenset({
    0o400, 0o440, 0o444, 0o500, 0o550, 0o555, 0o600, 0o640, 0o644,
    0o700, 0o750, 0o755,
})
REPAIR_PLAN = (
    "build_and_verify_signed_rollback_snapshot_from_manifest_bound_files",
    "obtain_owner_approval_for_exact_reported_path_removal",
    "remove_only_reported_unmanifested_files_without_following_symlinks",
    "rerun_immutable_release_preflight_before_any_release_apply",
)
OWNER_TOKEN_REPAIR_PLAN = (
    "provision_cryptographically_random_owner_token_out_of_band_without_output",
    "install_as_root_kolibri_agent_regular_non_symlink_mode_0640",
    "restart_only_kolibri_backend_after_canonical_dropin_is_installed",
    "run_owner_authenticated_api_smoke_without_printing_token",
)


class ImmutableReleasePreflightError(RuntimeError):
    """Sanitized structural error for operator-facing evidence."""

    def __init__(self, code: str):
        super().__init__(code)
        self.code = code


def _safe_relative(value: object) -> str:
    if not isinstance(value, str) or not value or "\\" in value or "\x00" in value:
        raise ImmutableReleasePreflightError("immutable_release_manifest_invalid")
    path = PurePosixPath(value)
    if path.is_absolute() or any(part in {"", ".", ".."} for part in path.parts):
        raise ImmutableReleasePreflightError("immutable_release_manifest_invalid")
    return path.as_posix()


def _trusted_directory(path: Path, *, owner: int | None = None) -> os.stat_result:
    try:
        value = path.lstat()
    except OSError as exc:
        raise ImmutableReleasePreflightError("immutable_release_boundary_invalid") from exc
    expected_owner = os.geteuid() if owner is None else owner
    if (
        not stat.S_ISDIR(value.st_mode)
        or stat.S_ISLNK(value.st_mode)
        or value.st_uid != expected_owner
        or value.st_mode & 0o022
    ):
        raise ImmutableReleasePreflightError("immutable_release_boundary_invalid")
    return value


def _load_manifest(release_dir: Path, owner: int) -> tuple[dict[str, Any], bytes]:
    path = release_dir / MANIFEST_PATH
    try:
        value = path.lstat()
        if (
            not stat.S_ISREG(value.st_mode)
            or stat.S_ISLNK(value.st_mode)
            or value.st_nlink != 1
            or value.st_uid != owner
            or value.st_mode & 0o022
            or not 0 < value.st_size <= MAX_MANIFEST_BYTES
        ):
            raise ImmutableReleasePreflightError("immutable_release_manifest_invalid")
        raw = path.read_bytes()
        manifest = json.loads(raw)
        canonical = json.dumps(
            manifest,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        ).encode("utf-8")
    except ImmutableReleasePreflightError:
        raise
    except (OSError, UnicodeError, json.JSONDecodeError, TypeError, ValueError) as exc:
        raise ImmutableReleasePreflightError("immutable_release_manifest_invalid") from exc
    if (
        not isinstance(manifest, dict)
        or manifest.get("schema_version") != RELEASE_SCHEMA
        or canonical != raw
        or manifest.get("release_id") != release_dir.name
        or not isinstance(manifest.get("files"), list)
    ):
        raise ImmutableReleasePreflightError("immutable_release_manifest_invalid")
    return manifest, raw


def _manifest_records(manifest: dict[str, Any]) -> dict[str, dict[str, Any]]:
    records: dict[str, dict[str, Any]] = {}
    for item in manifest["files"]:
        if not isinstance(item, dict):
            raise ImmutableReleasePreflightError("immutable_release_manifest_invalid")
        relative = _safe_relative(item.get("path"))
        sha256 = item.get("sha256")
        size = item.get("size_bytes")
        mode_text = item.get("mode")
        try:
            mode = int(mode_text, 8) if isinstance(mode_text, str) else -1
        except ValueError as exc:
            raise ImmutableReleasePreflightError("immutable_release_manifest_invalid") from exc
        if (
            relative in records
            or not isinstance(sha256, str)
            or not SAFE_SHA256.fullmatch(sha256)
            or type(size) is not int
            or size < 0
            or not isinstance(mode_text, str)
            or not re.fullmatch(r"0[0-7]{3}", mode_text)
            or mode not in SAFE_MODES
        ):
            raise ImmutableReleasePreflightError("immutable_release_manifest_invalid")
        records[relative] = item
    if not records:
        raise ImmutableReleasePreflightError("immutable_release_manifest_invalid")
    return records


def inspect_current(
    *,
    current: Path = DEFAULT_CURRENT,
    release_root: Path = DEFAULT_RELEASE_ROOT,
) -> dict[str, Any]:
    try:
        root = release_root.resolve(strict=True)
        current_value = current.lstat()
        release_dir = current.resolve(strict=True)
    except OSError as exc:
        raise ImmutableReleasePreflightError("immutable_release_current_invalid") from exc
    root_value = _trusted_directory(root)
    if (
        not stat.S_ISLNK(current_value.st_mode)
        or current_value.st_uid != root_value.st_uid
        or release_dir.parent != root
        or release_dir == root
        or not SAFE_RELEASE_ID.fullmatch(release_dir.name)
    ):
        raise ImmutableReleasePreflightError("immutable_release_current_invalid")
    _trusted_directory(release_dir, owner=root_value.st_uid)
    manifest, manifest_bytes = _load_manifest(release_dir, root_value.st_uid)
    expected = _manifest_records(manifest)
    actual: dict[str, Path] = {}
    metadata: set[str] = set()
    unsafe_paths: list[str] = []
    for path in release_dir.rglob("*"):
        relative = path.relative_to(release_dir).as_posix()
        try:
            value = path.lstat()
        except OSError:
            unsafe_paths.append(relative)
            continue
        if stat.S_ISLNK(value.st_mode):
            unsafe_paths.append(relative)
            continue
        if stat.S_ISDIR(value.st_mode):
            if value.st_uid != root_value.st_uid or value.st_mode & 0o022:
                unsafe_paths.append(relative)
            continue
        if not stat.S_ISREG(value.st_mode) or value.st_nlink != 1:
            unsafe_paths.append(relative)
            continue
        if relative.startswith(".kolibri-release/"):
            metadata.add(relative)
        else:
            actual[relative] = path

    integrity_errors: list[dict[str, str]] = []
    for relative, record in expected.items():
        path = actual.get(relative)
        if path is None:
            integrity_errors.append({"path": relative, "reason": "missing"})
            continue
        try:
            value = path.lstat()
            payload = path.read_bytes()
        except OSError:
            integrity_errors.append({"path": relative, "reason": "unreadable"})
            continue
        if value.st_uid != root_value.st_uid:
            integrity_errors.append({"path": relative, "reason": "owner"})
        if value.st_size != record["size_bytes"]:
            integrity_errors.append({"path": relative, "reason": "size"})
        if f"{stat.S_IMODE(value.st_mode):04o}" != record["mode"]:
            integrity_errors.append({"path": relative, "reason": "mode"})
        if hashlib.sha256(payload).hexdigest() != record["sha256"]:
            integrity_errors.append({"path": relative, "reason": "sha256"})

    extra_paths = sorted(set(actual) - set(expected))
    missing_paths = sorted(set(expected) - set(actual))
    metadata_valid = metadata == {MANIFEST_PATH, SIGNATURE_PATH}
    status = "passed"
    reason: str | None = None
    if unsafe_paths:
        status, reason = "blocked", "immutable_release_unsafe_path"
    elif not metadata_valid:
        status, reason = "blocked", "immutable_release_metadata_set_mismatch"
    elif integrity_errors or missing_paths:
        status, reason = "blocked", "immutable_release_integrity_mismatch"
    elif extra_paths:
        status, reason = "blocked", "immutable_release_file_set_polluted"

    result: dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "status": status,
        "mutation": "none",
        "release_id": release_dir.name,
        "manifest_digest": f"sha256:{hashlib.sha256(manifest_bytes).hexdigest()}",
        "manifest_file_total": len(expected),
        "actual_payload_file_total": len(actual),
        "extra_file_total": len(extra_paths),
        "missing_file_total": len(missing_paths),
        "integrity_error_total": len(integrity_errors),
        "unsafe_path_total": len(unsafe_paths),
        "metadata_exact": metadata_valid,
    }
    if reason is not None:
        result.update({
            "reason": reason,
            "reported_extra_paths": extra_paths[:MAX_REPORTED_PATHS],
            "reported_missing_paths": missing_paths[:MAX_REPORTED_PATHS],
            "reported_integrity_errors": integrity_errors[:MAX_REPORTED_PATHS],
            "reported_unsafe_paths": sorted(unsafe_paths)[:MAX_REPORTED_PATHS],
            "reported_paths_truncated": any(
                len(values) > MAX_REPORTED_PATHS
                for values in (extra_paths, missing_paths, integrity_errors, unsafe_paths)
            ),
            "repair_plan": list(REPAIR_PLAN),
        })
    return result


def inspect_owner_token_metadata(
    path: Path,
    *,
    expected_uid: int,
    expected_gid: int,
) -> dict[str, Any]:
    try:
        parent = path.parent.lstat()
        value = path.lstat()
    except FileNotFoundError as exc:
        raise ImmutableReleasePreflightError("owner_api_token_file_missing") from exc
    except OSError as exc:
        raise ImmutableReleasePreflightError("owner_api_token_file_unavailable") from exc
    if (
        not stat.S_ISDIR(parent.st_mode)
        or stat.S_ISLNK(parent.st_mode)
        or parent.st_uid != expected_uid
        or parent.st_mode & 0o022
        or not stat.S_ISREG(value.st_mode)
        or stat.S_ISLNK(value.st_mode)
        or value.st_nlink != 1
        or value.st_uid != expected_uid
        or value.st_gid != expected_gid
        or stat.S_IMODE(value.st_mode) != OWNER_TOKEN_MODE
        or not 1 <= value.st_size <= MAX_OWNER_TOKEN_BYTES
    ):
        raise ImmutableReleasePreflightError("owner_api_token_file_permissions_invalid")
    return {
        "owner_token_file": "metadata_verified_without_secret_read",
        "owner_token_mode": "0640",
        "owner_token_group": DEFAULT_OWNER_TOKEN_GROUP,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--current", default=str(DEFAULT_CURRENT))
    parser.add_argument("--release-root", default=str(DEFAULT_RELEASE_ROOT))
    parser.add_argument("--owner-token", default=str(DEFAULT_OWNER_TOKEN))
    parser.add_argument("--owner-token-group", default=DEFAULT_OWNER_TOKEN_GROUP)
    args = parser.parse_args(argv)
    try:
        result = inspect_current(
            current=Path(args.current),
            release_root=Path(args.release_root),
        )
        try:
            owner_group = grp.getgrnam(args.owner_token_group)
        except KeyError as exc:
            raise ImmutableReleasePreflightError("owner_api_token_group_missing") from exc
        token = inspect_owner_token_metadata(
            Path(args.owner_token),
            expected_uid=os.geteuid(),
            expected_gid=owner_group.gr_gid,
        )
        result.update(token)
    except ImmutableReleasePreflightError as exc:
        result = {
            "schema_version": SCHEMA_VERSION,
            "status": "blocked",
            "mutation": "none",
            "reason": exc.code,
            "repair_plan": list(REPAIR_PLAN),
        }
        if exc.code.startswith("owner_api_token_"):
            result["repair_plan"] = list(OWNER_TOKEN_REPAIR_PLAN)
    print(json.dumps(result, sort_keys=True))
    return 0 if result.get("status") == "passed" else 2


if __name__ == "__main__":
    raise SystemExit(main())
